import fs from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { loadVaultConfig } from "./config.js";
import { recordSession } from "./logs.js";
import { parseStoredPage } from "./pages.js";
import type { GraphArtifact, GraphEdge, GraphNode, GraphPage, PromotionGateResult } from "./types.js";
import { ensureDir, fileExists, readJsonFile, slugify, toPosix, uniqueBy, writeJsonFile } from "./utils.js";

export interface OutputPromotionResult { outputSlug: string; outputPath: string; pageId: string; title: string; path: string; sourceIds: string[]; gates: PromotionGateResult[]; merged: boolean; }
function uniqueStrings(values: string[]): string[] { return [...new Set(values.filter(Boolean))].sort((a, b) => a.localeCompare(b)); }
function outputSlugToPath(slug: string): string { return path.posix.join("outputs", `${slug.replace(/\\/g, "/").replace(/^outputs\//, "").replace(/\.md$/, "")}.md`); }
async function resolveConceptSlug(wikiDir: string, seed: string): Promise<string> { const root = slugify(seed) || "synthesis"; let candidate = root; for (let i = 2; await fileExists(path.join(wikiDir, "concepts", `${candidate}.md`)); i++) candidate = `${root}-${i}`; return candidate; }
function outputGates(output: GraphPage, graph: GraphArtifact): PromotionGateResult[] { const degree = Math.max(0, ...output.nodeIds.map((id) => graph.nodes.find((node) => node.id === id)?.degree ?? 0)); return [{ gate: "sources", value: output.sourceIds.length, threshold: 1, passed: output.sourceIds.length >= 1 }, { gate: "confidence", value: output.confidence, threshold: 0.5, passed: output.confidence >= 0.5 }, { gate: "degree", value: degree, threshold: 0, passed: true }, { gate: "age", value: 0, threshold: 0, passed: true }]; }
function conceptNodeFor(page: GraphPage): GraphNode { return { id: page.nodeIds[0] ?? page.id, type: "concept", label: page.title, pageId: page.id, freshness: page.freshness, confidence: page.confidence, sourceIds: page.sourceIds, projectIds: page.projectIds, degree: 0 }; }
function outputNodeFor(page: GraphPage): GraphNode { return { id: page.id, type: "output", label: page.title, pageId: page.id, freshness: page.freshness, confidence: page.confidence, sourceIds: page.sourceIds, projectIds: page.projectIds, degree: 0 }; }
function derivesFromEdges(page: GraphPage, output: GraphPage, node: GraphNode): GraphEdge[] { return uniqueStrings([output.id, ...output.sourceIds.map((id) => `source:${id}`)]).map((target) => ({ id: `${node.id}->${target}:derives_from`, source: node.id, target, relation: "derives_from", status: "inferred", evidenceClass: "inferred", confidence: page.confidence, provenance: uniqueStrings([output.id, ...output.sourceIds]) })); }
function appendSynthesisSection(existing: string, title: string, slug: string, body: string): string { return [existing.trimEnd(), "", "## Synthesis from query", "", `Source output: [[outputs/${slug}|${title}]]`, "", body.trim(), ""].join("\n"); }
async function updateOutputFrontmatter(file: string, promotedPath: string): Promise<string> { const parsed = matter(await fs.readFile(file, "utf8")); const next = matter.stringify(parsed.content, { ...parsed.data, promoted_to: promotedPath.replace(/\.md$/, ""), updated_at: new Date().toISOString() }); await fs.writeFile(file, next, "utf8"); return next; }

export async function promoteOutput(rootDir: string, slug: string, options: { into?: string } = {}): Promise<OutputPromotionResult> {
  const startedAt = new Date().toISOString(); const { paths } = await loadVaultConfig(rootDir);
  const graph = (await readJsonFile<GraphArtifact>(paths.graphPath)) ?? { generatedAt: startedAt, nodes: [], edges: [], hyperedges: [], sources: [], pages: [] };
  const outputPath = outputSlugToPath(slug); const outputAbsolutePath = path.join(paths.wikiDir, outputPath); const outputRaw = await fs.readFile(outputAbsolutePath, "utf8"); const outputParsed = matter(outputRaw);
  const outputPage = graph.pages.find((page) => page.kind === "output" && page.path === outputPath) ?? parseStoredPage(outputPath, outputRaw, { createdAt: startedAt, updatedAt: startedAt });
  const outputSlug = outputPath.replace(/^outputs\//, "").replace(/\.md$/, ""); const now = new Date().toISOString(); let conceptRaw: string; let conceptPath: string; let merged = false;
  if (options.into) {
    const intoSlug = options.into.replace(/^concepts\//, "").replace(/\.md$/, ""); conceptPath = path.posix.join("concepts", `${intoSlug}.md`); const conceptAbsolutePath = path.join(paths.wikiDir, conceptPath); const existing = matter(await fs.readFile(conceptAbsolutePath, "utf8")); const previous = Array.isArray(existing.data.superseded_by_synthesis) ? existing.data.superseded_by_synthesis : [];
    conceptRaw = matter.stringify(appendSynthesisSection(existing.content, outputPage.title, outputSlug, outputParsed.content), { ...existing.data, source_ids: uniqueStrings([...outputPage.sourceIds, ...((Array.isArray(existing.data.source_ids) ? existing.data.source_ids : []) as string[])]), compiled_from: uniqueStrings([...outputPage.sourceIds, ...((Array.isArray(existing.data.compiled_from) ? existing.data.compiled_from : []) as string[])]), superseded_by_synthesis: uniqueStrings([...previous, `outputs/${outputSlug}`]), updated_at: now }); await fs.writeFile(conceptAbsolutePath, conceptRaw, "utf8"); merged = true;
  } else {
    const conceptSlug = await resolveConceptSlug(paths.wikiDir, outputPage.title || outputSlug); conceptPath = path.posix.join("concepts", `${conceptSlug}.md`); const conceptAbsolutePath = path.join(paths.wikiDir, conceptPath); await ensureDir(path.dirname(conceptAbsolutePath));
    conceptRaw = matter.stringify(outputParsed.content.trim(), { title: outputPage.title, page_id: `concept:${conceptSlug}`, kind: "concept", status: "active", source_ids: outputPage.sourceIds, project_ids: outputPage.projectIds, node_ids: [`concept:${conceptSlug}`], freshness: "fresh", confidence: outputPage.confidence, schema_hash: outputPage.schemaHash, source_hashes: outputPage.sourceHashes, source_semantic_hashes: outputPage.sourceSemanticHashes, related_page_ids: [outputPage.id], related_node_ids: outputPage.nodeIds, related_source_ids: outputPage.relatedSourceIds.length ? outputPage.relatedSourceIds : outputPage.sourceIds, compiled_from: outputPage.sourceIds, managed_by: "system", derived_from: `outputs/${outputSlug}`, created_at: now, updated_at: now, tags: ["concept", "synthesis"] }); await fs.writeFile(conceptAbsolutePath, conceptRaw, "utf8");
  }
  const outputNextRaw = await updateOutputFrontmatter(outputAbsolutePath, conceptPath); const conceptPage = parseStoredPage(conceptPath, conceptRaw, { createdAt: now, updatedAt: now }); const outputNextPage = parseStoredPage(outputPath, outputNextRaw, { createdAt: outputPage.createdAt, updatedAt: now }); const conceptNode = conceptNodeFor(conceptPage); const outputNode = outputNodeFor(outputNextPage); const newEdges = derivesFromEdges(conceptPage, outputNextPage, conceptNode); const newEdgeIds = new Set(newEdges.map((edge) => edge.id));
  await writeJsonFile(paths.graphPath, { ...graph, generatedAt: now, nodes: uniqueBy(graph.nodes.filter((node) => node.id !== conceptNode.id && node.id !== outputNode.id).concat([conceptNode, outputNode]), (node) => node.id), edges: graph.edges.filter((edge) => !newEdgeIds.has(edge.id)).concat(newEdges), pages: graph.pages.filter((page) => page.id !== conceptPage.id && page.path !== conceptPath && page.id !== outputNextPage.id && page.path !== outputPath).concat([conceptPage, outputNextPage]).sort((a, b) => a.path.localeCompare(b.path)) });
  await recordSession(rootDir, { operation: "query", title: `Promoted ${outputPath}`, startedAt, finishedAt: new Date().toISOString(), success: true, relatedPageIds: [outputNextPage.id, conceptPage.id], changedPages: [outputPath, conceptPath], lines: [`output=${outputPath}`, `concept=${conceptPath}`, `mode=${merged ? "merge" : "create"}`] });
  return { outputSlug, outputPath, pageId: conceptPage.id, title: conceptPage.title, path: toPosix(conceptPath), sourceIds: conceptPage.sourceIds, gates: outputGates(outputPage, graph), merged };
}
